
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcqxucvaepbksgmipxst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjcXh1Y3ZhZXBia3NnbWlweHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzE4MDksImV4cCI6MjA2MzE0NzgwOX0.FjspgdfrFNTLatvcJjghdHbLQQ2dK0TVjoTK9YPa78U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage, // Using localStorage for session persistence
  }
});
